### ISSUE TITLE
Magit maintainer's wishlist

### ISSUE THREAD

**Issue by tarsius** [magit/libegit2#25]
If you are looking for something to implement, these are some of the functions that I expect would be most useful for Magit.

- [x] `libgit-repository-discover` (`start-path` should be optional and default to `default-directory`)

(Okay so that's a pretty short list right now. But I really really need this one, so I am opening this issue before actually having compiled a list. More will be added later.)

- [ ] Equivalent of `git rev-parse --git-dir|--show-toplevel|--show-cdup` (which may already exist, but I cannot find them)
- [x] `libgit-branch-*` especially `*-name`.
- [x] `libgit-describe-*`

**Comment by TheBB** [comment]
I did `libgit-repository-discover` for you. Lists are a bit of a nuisance in C so hopefully it all works correctly.

**Comment by TheBB** [comment]
As for the *rev-parse* stuff, I don't think libgit2 considers the higher-level git commands to be in scope for their project, so if we want that we probably have to roll it ourselves.

I'm not super familiar with the details of those options but I'm *guessing* we can replicate the functionality more or less like this (here, from my `~/.emacs.d/lib` path):

    (libgit-repository-discover "~/.emacs.d/lib")
    => "/home/eivind/.emacs.d/.git/"

    (libgit-repository-workdir (libgit-repository-open (libgit-repository-discover "~/.emacs.d/lib")))
    => "/home/eivind/.emacs.d/"

    (file-relative-name
     (libgit-repository-workdir (libgit-repository-open (libgit-repository-discover "~/.emacs.d/lib")))
     "~/.emacs.d/lib")
    => "../"

And with `git`:

    eivind@cauchy  ~/.emacs.d/lib
    -> % git rev-parse --git-dir      
    /home/eivind/.emacs.d/.git

    eivind@cauchy  ~/.emacs.d/lib
    -> % git rev-parse --show-toplevel
    /home/eivind/.emacs.d

    eivind@cauchy  ~/.emacs.d/lib
    -> % git rev-parse --show-cdup    
    ../
