### ISSUE TITLE
Unreachable prompt due to libgit.el in Magit borg-build buffer

### ISSUE THREAD

**Issue by cloudchin** [magit/libegit2#90]
Not sure if related to [83](https://github.com/magit/libegit2/issues/83). (I don't think I have cmake installed on mingw)

Version: `mingw-w64-x86_64-emacs 26.3` installed via pacman & run from a mingw64 prompt

Installed borg, was slowly going through initial code reviews & update-flow, decided I was okay to try and pull down latest magit commits.  The borg-build buffer is read-only, and I was prompted to re-build libgit, but the buffer doesn't accept user input. (See attached.) Unfortunately, it seems it has had other side-effects not easily measured, as Magit now no longer lists itself under the `Modules unpulled from`, even though `borg-build magit` still hangs due to the hanging prompt.

I read thru magit-git.el, borg.el, and libgit.el, and am a little over my head, but it seems like it maybe in `libgit--configure` which references cmake...? I'll check my toolchain and will report back, but that kind of dependency is very non-obvious for someone coming by-way of the borg manual fresh out of the gates!

[magit-build-fail-20200222.txt](https://github.com/magit/libegit2/files/4240400/magit-build-fail-20200222.txt)

Thank you for your amazing contributions btw. Stellar code and programs, all considered.

**Comment by tarsius** [comment]
You have to add an explicit build-step for this package: `git config -f .submodules submodule.libgit.build-step make`. And then you should probably build it explicitly once: `make lib/libgit` and then rebuild the rest `make clean all`?

We should however also prevent interactive questions in non-interactive emacs instances.
