### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Apteryks** [magit/libegit2#91]
Looking at the LICENSE file, it seems to be GPL v2 or later.  Looking at libgit.el, it seems to be GPL v3 or later.  Which is correct / up to date?

**Comment by tarsius** [comment]
Libgit2 itself is released under `GPL-2.0` with a linking exception, which allows it to be linked even with proprietary programs, see https://github.com/libgit2/libgit2/blob/main/COPYING.

The FSF considers emacs-lisp packages to derive from Emacs. I expect this extends to C modules. They do not insist that emacs-lisp packages are released under `GPL-3.0-only` or `GPL-3.0-or-later`, but expect a compatible license to be used. `GPL-2.0-only` is not compatible, but `GPL-2.0-or-later` is.

I think we should be as permissive as possible to avoid looking ourselves in down the road, so we should use `GPL-2.0-or-later`.

`src/main.c` already contains `int plugin_is_GPL_compatible;`, so I believe that means that we have already stated that the C code is released under `GPL-2.0-or-later`, not just `GPL-2.0-only`.

We should release the elisp part under the same license, but as you noticed, it currently says `GPL-3.0-or-later`. @TheBB, @wyuenho, @Miciah and I have made changes to that file. Are you all okay with changing the license of `libgit.el` from `GPL-3.0-or-later` to `GPL-2.0-or-later`?

**Comment by wyuenho** [comment]
Sounds good to me

**Comment by TheBB** [comment]
Yes, no problem.

**Comment by tarsius** [comment]
Done. (We don't have to wait for @Miciah, all they contributed is 3213b37c228731b0acfdda67dff3905a65a8a581.)
